:so $HOME/dotfiles/vimrc_win64/ryan/plugins.vim
:so $HOME/dotfiles/vimrc_win64/ryan/settings.vim
:so $HOME/dotfiles/vimrc_win64/ryan/mappings.vim
:so $HOME/dotfiles/vimrc_win64/ryan/abbrs.vim

source $VIMRUNTIME/vimrc_example.vim
source $VIMRUNTIME/mswin.vim
behave mswin

	
